### ISSUE TITLE
Any way to get this to work when behind a corporate http proxy?

### ISSUE THREAD

**Issue by sean256** [joona/aws-es-proxy#1]
I get timeout errors when behind my company proxy.

**Comment by joona** [comment]
This should pretty much work out of the box, if you have proxy configured on the local machine to port all HTTP connections over (AWS ES Service is listening on port 80). In case separate HTTP proxy needs to be explicitly configured, you can try my http-proxy branch to see if it works.

https://github.com/joona/aws-es-proxy/tree/http-proxy

specify `--http-proxy http://foo.bar` option to the request and it will apply proxy configuration to AWS sdk, which is handling the connection under the hood.
