### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by nekloth** [joona/aws-es-proxy#4]
Can we have an option to not display request into the console ? 

I use this component to migrate data from one source to a target (2 instances of the proxy launched on 2 different ports), and using Elasticdump tool, but it slows down as it has to write both requests in terminal (GET/POST)...

**Comment by joona** [comment]
Thanks for your request! Seems that I was also mistakenly logging outputs of the requests, which will definitely make things slow when migrating data to another index.

I added `--quiet` option, which will also turn off logging of the sent requests.

For running ES migrations, [joona/es-schema-migration](https://github.com/joona/es-schema-migration) might come in handy as well...
